name: Build
on: [push, pull_request]
env:
  zig_version: 0.8.1

jobs:
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ env.zig_version }}
      - run: sudo apt-get install libsdl2-dev # Prevents us from running on all platforms
      - run: zig build
      - run: zig build test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ env.zig_version }}
      - run: zig fmt --check src/*.zig
